trigger:
  batch: 'true'
  branches:
    include:
    - master
    - develop

pr:
  branches:
    include:
    - master
    - develop

stages:
- stage: 'Build'
  jobs:
  - job: 'Windows_job'
    timeoutInMinutes: '10'
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - checkout: self
      lfs: 'true'
      submodules: 'true'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '$(solution)'
        feedsToUse: 'select'
        vstsFeed: 'da83dbac-97ca-4698-b2c1-fdeba0531acd'
      displayName: "Restore NuGet packages"

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) --no-restore'
      displayName: "Build projects"